CREATE TABLE Director
(
    director_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)                         not null,
    age         int check ( age > 18 and age < 100 ) not null
);

CREATE TABLE Movie
(
    movie_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_id        bigint                                  not null references Director (director_id) on delete cascade,
    name               VARCHAR(100)                            not null,
    year_of_production int check ( year_of_production > 1900 ) not null
);

CREATE TABLE Actor
(
    actor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100)                         not null,
    age      int check ( age > 18 and age < 100 ) not null
);

CREATE TABLE Movie_Actor
(
    actor_id bigint references Actor (actor_id) on delete cascade,
    movie_id bigint references Movie (movie_id) on delete cascade,
    primary key (actor_id, movie_id)
);